export const ADD_TRXN = "ADD_TRXN";
export const EDIT_TRXN = "DELETE_TODO";
export const DELETE_TRXN = "DELETE_TODO";
export const GET_EXPENSES_LIST_SERVER = "GET_EXPENSES_LIST_SERVER";
export const RENDER_EXPENSES_LIST_SERVER = "RENDER_EXPENSES_LIST_SERVER";